### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by zhangyedi** [teobaluta/NPAQ#11]
When I run the example you give, "python npaq bnn --arch 1blk_100 --dataset mnist --resize 10,10 quant-robust 2", the result shows as follows:

Counting done. Saving witnesses...
Traceback (most recent call last):
  File "NPAQ-master/npaq/__main__.py", line 8, in <module>
    args.func(args)
  File "npaq/arg_parser.py", line 450, in parse_robustness
    enc_strategy=args.encoder)
  File "npaq/properties.py", line 188, in quantify_robustness
    dir_samples, dir_imgs = witness.save_witness(dataset, formula_fname, nn)
  File "npaq/witness.py", line 15, in save_witness
    _, samples_fname = utils.get_output_fnames(formula_fname)
ValueError: too many values to unpack

**Comment by teobaluta** [comment]
Thanks! Pushed the fix.
